#!/usr/bin/env bash
tail -25 $SQUATES_FILE | ruby -ne '
require "date"
require "colorize"
regex = Regexp.new DateTime.now.strftime("%d.%m.%Y")
if regex === $_
    print $_.green
else
    print $_.yellow
end

'